[config.paths]
results_dir_name = "results"
cache_dir_name = "cache"

[config.hydra_zen]
verbose = true

[config.dm.shared]
force_reprocess = false
num_conversations = 2

[config.dm.MaptaskVADM]
batch_size = 32
train_split = 0.8

[config.dm.MaptaskPauseDM]
batch_size = 32
train_split = 0.8

[config.model.full]
num_layers = 1
hidden_dim = 40

[config.model.prosody]
num_layers = 1
hidden_dim = 10

[config.pl.trainer]
log_every_n_steps = 1
max_epochs = 1000
accelerator = "auto"

[experiment.41]
experiment_name = "experiment_41"
seed = 42
sequence_length_ms = [60_000]
prediction_length_ms = [250, 500, 1000, 2000, 3000]
target_participants = ["f", "g"]